<x-layouts.admin :title="$account->displayLabel().' | Cherry Bellemont'">
    <x-admin.section width="7xl">
        <x-admin.page-header eyebrow="Chart of Accounts" :title="$account->displayLabel()" subtitle="Account classification and lifecycle details.">
            <x-slot:actions><x-admin.button variant="outline" :href="route('admin.accounting.accounts.index')">All Accounts</x-admin.button><x-admin.button :href="route('admin.accounting.accounts.edit', $account)" icon="bi-pencil">Edit Account</x-admin.button></x-slot:actions>
        </x-admin.page-header>

        <div class="mt-8 grid gap-6 lg:grid-cols-3">
            <x-admin.card class="lg:col-span-2" title="Account details"><dl class="grid gap-x-8 gap-y-5 sm:grid-cols-2"><div><dt class="admin-label">Account type</dt><dd>{{ str($account->type)->replace('_', ' ')->title() }}</dd></div><div><dt class="admin-label">Account subtype</dt><dd>{{ $account->subtype ?: '—' }}</dd></div><div><dt class="admin-label">Normal balance</dt><dd>{{ str($account->normal_balance)->title() }}</dd></div><div><dt class="admin-label">Parent account</dt><dd>@if($account->parent)<a class="text-gold" href="{{ route('admin.accounting.accounts.show', $account->parent) }}">{{ $account->parent->displayLabel() }}</a>@else — @endif</dd></div><div><dt class="admin-label">Opening balance</dt><dd>RM {{ number_format((float) $account->opening_balance, 2) }} @if($account->opening_balance_date)<span class="text-cream/60">as at {{ $account->opening_balance_date->format('d M Y') }}</span>@endif</dd></div><div><dt class="admin-label">Manual posting</dt><dd>{{ $account->allow_manual_posting ? 'Allowed' : 'Not allowed' }}</dd></div><div><dt class="admin-label">Status</dt><dd><x-admin.badge :status="$account->is_active ? 'active' : 'inactive'" /></dd></div><div><dt class="admin-label">Ownership</dt><dd><x-admin.badge :status="$account->is_system ? 'processing' : 'pending'" :label="$account->is_system ? 'System account' : 'Custom account'" /></dd></div><div class="sm:col-span-2"><dt class="admin-label">Description</dt><dd>{{ $account->description ?: 'No description provided.' }}</dd></div></dl></x-admin.card>
            <x-admin.card title="Future ledger information"><div class="space-y-4 text-sm text-cream/70"><div><p class="font-medium text-cream">Current Ledger Balance</p><p class="mt-1">Available after posted Journal Entries and the General Ledger are used.</p></div><div><p class="font-medium text-cream">Total Debits / Credits</p><p class="mt-1">Not calculated on this account page to avoid presenting incomplete financial data.</p></div><div><p class="font-medium text-cream">Last Posted Transaction</p><p class="mt-1">{{ $account->lines_count ? 'View General Ledger when reviewing posted activity.' : 'No journal activity recorded.' }}</p></div></div></x-admin.card>
        </div>
        <div class="mt-6 grid gap-6 lg:grid-cols-2"><x-admin.card title="Child accounts">@forelse($account->children as $child)<a class="block border-b border-cream/10 py-3 text-gold hover:text-cream" href="{{ route('admin.accounting.accounts.show', $child) }}">{{ $child->displayLabel() }}</a>@empty<p class="text-sm text-cream/60">No child accounts.</p>@endforelse</x-admin.card><x-admin.card title="Audit details"><dl class="space-y-4 text-sm"><div><dt class="admin-label">Created</dt><dd>{{ $account->created_at?->format('d M Y, H:i') }} @if($account->creator) by {{ $account->creator->name }}@endif</dd></div><div><dt class="admin-label">Last updated</dt><dd>{{ $account->updated_at?->format('d M Y, H:i') }} @if($account->updater) by {{ $account->updater->name }}@endif</dd></div></dl></x-admin.card></div>
    </x-admin.section>
</x-layouts.admin>
