@php($money = fn (int $cents) => 'RM '.number_format($cents / 100, 2))
<x-layouts.admin title="Cash Flow | Cherry Bellemont">
    <x-admin.section width="7xl">
        <x-admin.page-header eyebrow="Accounting" title="Cash Flow" subtitle="Direct-method cash reporting from posted journals. Profit is not the same as cash: capital, drawings, accruals and internal transfers are treated separately.">
            <x-slot:actions>
                <x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.reconciliation', $filters)" icon="bi-arrow-left-right">Reconciliation</x-admin.button>
                <x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.diagnostics', $filters)" icon="bi-shield-exclamation">Diagnostics</x-admin.button>
                <x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.print', $filters)" icon="bi-printer" target="_blank">Print</x-admin.button>
            </x-slot:actions>
        </x-admin.page-header>

        <x-admin.card class="mt-8" title="Cash Flow filters">
            <form class="grid gap-4 md:grid-cols-2 xl:grid-cols-5" method="GET" action="{{ route('admin.accounting.cash-flow.index') }}">
                <x-admin.select name="range" label="Date shortcut"><option value="today" @selected(($filters['range'] ?? '') === 'today')>Today</option><option value="this_week" @selected(($filters['range'] ?? '') === 'this_week')>This Week</option><option value="this_month" @selected(($filters['range'] ?? '') === 'this_month')>This Month</option><option value="last_month" @selected(($filters['range'] ?? '') === 'last_month')>Last Month</option><option value="this_quarter" @selected(($filters['range'] ?? '') === 'this_quarter')>This Quarter</option><option value="this_year" @selected(($filters['range'] ?? 'this_year') === 'this_year')>This Year</option><option value="last_year" @selected(($filters['range'] ?? '') === 'last_year')>Last Year</option><option value="custom" @selected(($filters['range'] ?? '') === 'custom')>Custom range</option></x-admin.select>
                <x-admin.form-input name="from_date" type="date" label="Start date" :value="$filters['from_date'] ?? null" />
                <x-admin.form-input name="to_date" type="date" label="End date" :value="$filters['to_date'] ?? null" />
                <x-admin.select name="cash_account_id" label="Cash account"><option value="">All included cash accounts</option>@foreach($report['cash_accounts'] as $account)<option value="{{ $account->id }}" @selected((string) ($filters['cash_account_id'] ?? '') === (string) $account->id)>{{ $account->displayLabel() }}</option>@endforeach</x-admin.select>
                <x-admin.select name="classification" label="Classification"><option value="">All classifications</option>@foreach(['operating' => 'Operating', 'investing' => 'Investing', 'financing' => 'Financing', 'internal_transfer' => 'Internal transfer', 'non_cash' => 'Non-cash', 'unclassified' => 'Unclassified'] as $value => $label)<option value="{{ $value }}" @selected(($filters['classification'] ?? '') === $value)>{{ $label }}</option>@endforeach</x-admin.select>
                <x-admin.select name="category" label="Category"><option value="">All categories</option>@foreach($categories as $key => $label)<option value="{{ $key }}" @selected(($filters['category'] ?? '') === $key)>{{ $label }}</option>@endforeach</x-admin.select>
                <x-admin.form-input name="source_type" label="Source type" :value="$filters['source_type'] ?? null" placeholder="e.g. order" />
                <x-admin.form-input name="journal_number" label="Journal number" :value="$filters['journal_number'] ?? null" />
                <x-admin.form-input name="reference" label="Reference" :value="$filters['reference'] ?? null" />
                <x-admin.form-input name="search" label="Search" :value="$filters['search'] ?? null" placeholder="Description or account" />
                <x-admin.form-input name="minimum_amount" label="Minimum amount" :value="$filters['minimum_amount'] ?? null" inputmode="decimal" />
                <x-admin.form-input name="maximum_amount" label="Maximum amount" :value="$filters['maximum_amount'] ?? null" inputmode="decimal" />
                <div class="flex flex-wrap items-end gap-4 xl:col-span-3"><label class="flex items-center gap-2 text-sm text-cream/85"><input type="hidden" name="include_clearing" value="0"><input type="checkbox" name="include_clearing" value="1" @checked($filters['include_clearing'] ?? true)> Include clearing accounts</label><label class="flex items-center gap-2 text-sm text-cream/85"><input type="hidden" name="include_internal_transfers" value="0"><input type="checkbox" name="include_internal_transfers" value="1" @checked($filters['include_internal_transfers'] ?? true)> Show internal transfers in detail</label><label class="flex items-center gap-2 text-sm text-cream/85"><input type="hidden" name="include_non_cash_activity" value="0"><input type="checkbox" name="include_non_cash_activity" value="1" @checked($filters['include_non_cash_activity'] ?? false)> Show non-cash activity</label></div>
                <div class="flex items-end gap-3 xl:col-span-2"><x-admin.button type="submit" icon="bi-funnel">Apply Filters</x-admin.button><x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.index')">Clear</x-admin.button></div>
            </form>
            @if($errors->any())<p class="mt-4 border border-red-300/40 bg-red-950/30 px-4 py-3 text-sm text-red-100">{{ $errors->first() }}</p>@endif
        </x-admin.card>

        @unless($report['has_cash_accounts'])
            <x-admin.card class="mt-8" title="Cash account setup required"><p class="text-cream/75">No active Chart of Accounts entry is marked for Cash Flow. Mark a debit-normal cash, bank, or cash-equivalent asset account as “Include in Cash Flow reports”.</p><div class="mt-5"><x-admin.button :href="route('admin.accounting.accounts.index')" icon="bi-list-columns">Open Chart of Accounts</x-admin.button></div></x-admin.card>
        @else
            <p class="mt-5 text-sm text-cream/65">Reporting period: <span class="text-gold">{{ $report['period']['label'] }}</span> · {{ $report['period']['start']->format('d M Y') }} to {{ $report['period']['end']->format('d M Y') }} · Direct method.</p>
            @if($report['reconciliation_difference'] !== 0)<div class="mt-5 border border-red-300/50 bg-red-950/30 px-5 py-4 text-red-100"><i class="bi bi-exclamation-triangle mr-2"></i>Cash Flow differs from General Ledger cash by {{ $money($report['reconciliation_difference']) }}. Review classification diagnostics before relying on the statement.</div>@endif
            @if($report['metrics']['unclassified'] > 0)<div class="mt-5 border border-gold/40 bg-wine-deep px-5 py-4 text-cream/85"><i class="bi bi-info-circle mr-2 text-gold"></i>{{ $money($report['metrics']['unclassified']) }} of cash activity remains unclassified. It is included in reconciliation but should be reviewed.</div>@endif

            <div class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
                <x-admin.stats-card label="Opening Cash" :value="$money($report['opening_cash'])" /><x-admin.stats-card label="Total Cash Inflow" :value="$money($report['cash_inflow'])" /><x-admin.stats-card label="Total Cash Outflow" :value="$money($report['cash_outflow'])" /><x-admin.stats-card label="Closing Cash" :value="$money($report['closing_cash'])" />
                <x-admin.stats-card label="Operating Cash Flow" :value="$money($report['metrics']['operating'])" /><x-admin.stats-card label="Investing Cash Flow" :value="$money($report['metrics']['investing'])" /><x-admin.stats-card label="Financing Cash Flow" :value="$money($report['metrics']['financing'])" /><x-admin.stats-card label="Reconciliation Difference" :value="$money($report['reconciliation_difference'])" :accent="$report['reconciliation_difference'] !== 0" />
                <x-admin.stats-card label="Refunds Paid" :value="$money($report['metrics']['refunds'])" /><x-admin.stats-card label="Owner Salary Paid" :value="$money($report['metrics']['salary'])" /><x-admin.stats-card label="Owner Drawings" :value="$money($report['metrics']['drawings'])" /><x-admin.stats-card label="Owner Capital Added" :value="$money($report['metrics']['capital'])" />
            </div>
            <div class="mt-8 flex flex-wrap gap-3"><x-admin.button :href="route('admin.accounting.cash-flow.statement', $filters)" icon="bi-file-earmark-bar-graph">Formal Statement</x-admin.button><x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.movements', $filters)" icon="bi-list-ul">Cash Movements</x-admin.button><x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.configuration')" icon="bi-sliders">Classifications</x-admin.button>@foreach(['csv' => 'CSV', 'xlsx' => 'Excel', 'pdf' => 'PDF'] as $format => $label)<x-admin.button variant="outline" :href="route('admin.accounting.cash-flow.export.statement', array_merge(['format' => $format], collect($filters)->except('page')->all()))" icon="bi-download">{{ $label }}</x-admin.button>@endforeach</div>

            <div class="mt-8 grid gap-6 xl:grid-cols-2"><x-admin.card title="Cash position by account"><x-admin.table class="mt-5"><x-slot:head><tr><th>Account</th><th>Opening</th><th>Cash In</th><th>Cash Out</th><th>Transfers</th><th>Closing</th><th></th></tr></x-slot:head>
                @foreach($report['positions'] as $position)<tr><td><span class="text-gold">{{ $position['account']->code }}</span> — {{ $position['account']->name }}</td><td>{{ $money($position['opening_balance']) }}</td><td>{{ $money($position['cash_in']) }}</td><td>{{ $money($position['cash_out']) }}</td><td>{{ $money($position['internal_transfers_in'] - $position['internal_transfers_out']) }}</td><td>{{ $money($position['closing_balance']) }}</td><td><a class="text-gold hover:text-cream" href="{{ route('admin.accounting.cash-flow.account', array_merge(['account' => $position['account']], collect($filters)->except('cash_account_id', 'page')->all())) }}">View</a></td></tr>@endforeach</x-admin.table></x-admin.card>
            <x-admin.card title="Reconciliation"><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between border-b border-cream/10 pb-3"><dt>Opening Cash from Ledger</dt><dd>{{ $money($report['opening_cash']) }}</dd></div><div class="flex justify-between border-b border-cream/10 pb-3"><dt>Net Cash Movement</dt><dd>{{ $money($report['net_cash_movement']) }}</dd></div><div class="flex justify-between border-b border-cream/10 pb-3"><dt>Expected Closing Cash</dt><dd>{{ $money($report['closing_cash']) }}</dd></div><div class="flex justify-between border-b border-cream/10 pb-3"><dt>General Ledger Closing Cash</dt><dd>{{ $money($report['general_ledger_closing_cash']) }}</dd></div><div class="flex justify-between font-semibold text-gold"><dt>Difference</dt><dd>{{ $money($report['reconciliation_difference']) }}</dd></div></dl></x-admin.card></div>
            <div class="mt-8 grid gap-6 xl:grid-cols-2"><x-admin.card title="Cash Inflow and Outflow"><div class="h-72"><canvas id="accounting-cash-flow-in-out-chart"></canvas></div></x-admin.card><x-admin.card title="Net Cash Movement"><div class="h-72"><canvas id="accounting-cash-flow-net-chart"></canvas></div></x-admin.card><x-admin.card title="Closing Cash Trend"><div class="h-72"><canvas id="accounting-cash-flow-closing-chart"></canvas></div></x-admin.card><x-admin.card title="Operating, Investing and Financing"><div class="h-72"><canvas id="accounting-cash-flow-classification-chart"></canvas></div></x-admin.card><x-admin.card title="Cash Outflow by Category"><div class="h-72"><canvas id="accounting-cash-flow-outflow-chart"></canvas></div></x-admin.card></div>
            <script id="accounting-cash-flow-chart-data" type="application/json">@json($report['charts'])</script>
        @endunless
    </x-admin.section>
</x-layouts.admin>
