<?php

use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CourierController;
use App\Http\Controllers\Admin\CustomerController as AdminCustomerController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\DeliveryMethodController;
use App\Http\Controllers\Admin\FaqController as AdminFaqController;
use App\Http\Controllers\Admin\NewsletterSubscriberController;
use App\Http\Controllers\Admin\NewsletterCampaignController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PaymentReceiptController as AdminPaymentReceiptController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ProductColourController as AdminProductColourController;
use App\Http\Controllers\Admin\ProductSizeController as AdminProductSizeController;
use App\Http\Controllers\Admin\ProductTagController as AdminProductTagController;
use App\Http\Controllers\Admin\ProductStockNotificationController as AdminProductStockNotificationController;
use App\Http\Controllers\Admin\ReportsController as AdminReportsController;
use App\Http\Controllers\Admin\ReviewController as AdminReviewController;
use App\Http\Controllers\Admin\ReturnRequestController as AdminReturnRequestController;
use App\Http\Controllers\Admin\ShippingZoneController;
use App\Http\Controllers\Admin\ShipmentController;
use App\Http\Controllers\Admin\SettingsController as AdminSettingsController;
use App\Http\Controllers\Admin\AccountingController as AdminAccountingController;
use App\Http\Controllers\Admin\AccountingAccountController;
use App\Http\Controllers\Admin\GeneralLedgerController;
use App\Http\Controllers\Admin\JournalEntryController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentReceiptController;
use App\Http\Controllers\ProductStockNotificationController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\ReturnRequestController;
use App\Http\Controllers\ShippingQuoteController;
use App\Http\Controllers\ShipmentTrackingController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\StorefrontController;
use App\Http\Controllers\StripeCheckoutController;
use App\Http\Controllers\StripeWebhookController;
use App\Mail\AdminOperationalPreviewMail;
use App\Mail\TransactionalPreviewMail;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Route;

Route::get('/', [StorefrontController::class, 'home'])->name('home');
Route::get('/sitemap.xml', SitemapController::class)->name('sitemap');
Route::get('/collection', [StorefrontController::class, 'collection'])->name('collection');
Route::redirect('/shop', '/collection');
Route::get('/collection/products/{product:slug}', [StorefrontController::class, 'show'])->name('products.show');
Route::post('/collection/{product:slug}/back-in-stock', [ProductStockNotificationController::class, 'store'])->middleware('throttle:6,1')->name('product-stock-notifications.store');
Route::get('/back-in-stock/cancel/{token}', [ProductStockNotificationController::class, 'cancel'])->name('product-stock-notifications.cancel');
Route::get('/collection/{product:slug}/review', [ReviewController::class, 'create'])->name('reviews.create');
Route::post('/collection/{product:slug}/review', [ReviewController::class, 'store'])->middleware('throttle:6,1')->name('reviews.store');
Route::patch('/collection/{product:slug}/reviews/{review}', [ReviewController::class, 'update'])->middleware('throttle:6,1')->name('reviews.update');
Route::get('/collection/{slug}', [StorefrontController::class, 'categoryOrLegacyProduct'])->name('collection.category');
Route::post('/reviews/{review}/helpful', [ReviewController::class, 'helpful'])->middleware('throttle:20,1')->name('reviews.helpful');
Route::view('/about', 'storefront.about')->name('about');
Route::get('/faq', [FaqController::class, 'index'])->name('faq.index');
Route::post('/newsletter/subscribe', [NewsletterController::class, 'subscribe'])->middleware('throttle:6,1')->name('newsletter.subscribe');
Route::get('/newsletter/unsubscribe/{token}', [NewsletterController::class, 'unsubscribe'])->name('newsletter.unsubscribe');
Route::view('/contact', 'storefront.information', ['title' => 'Contact', 'heading' => 'Contact Cherry Bellemont', 'message' => 'Our client care details are being prepared. Please return soon for assistance and contact information.'])->name('contact');
Route::view('/shipping-policy', 'policies.shipping')->name('shipping.policy');
Route::view('/refund-policy', 'policies.refund')->name('refund.policy');
Route::view('/privacy-policy', 'policies.privacy')->name('privacy.policy');
Route::view('/terms-and-conditions', 'policies.terms')->name('terms.policy');
Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
Route::post('/cart/coupon', [CartController::class, 'applyCoupon'])->middleware('throttle:10,1')->name('cart.coupon.apply');
Route::delete('/cart/coupon', [CartController::class, 'removeCoupon'])->name('cart.coupon.remove');
Route::post('/cart/{product}', [CartController::class, 'store'])->name('cart.store');
Route::patch('/cart/{product}', [CartController::class, 'update'])->name('cart.update');
Route::delete('/cart/{product}', [CartController::class, 'destroy'])->name('cart.destroy');
Route::delete('/cart', [CartController::class, 'clear'])->name('cart.clear');
Route::get('/checkout', [CheckoutController::class, 'create'])->name('checkout.create');
Route::post('/checkout', [CheckoutController::class, 'store'])->middleware('throttle:6,1')->name('checkout.store');
Route::post('/shipping/quote', ShippingQuoteController::class)->middleware('throttle:20,1')->name('shipping.quote');
Route::get('/orders/{order:number}/access/{token}', [OrderController::class, 'guestShow'])->name('orders.guest.show');
Route::get('/orders/{order:number}/access/{token}/confirmation', [OrderController::class, 'guestConfirmation'])->name('orders.guest.confirmation');
Route::get('/orders/{order:number}/access/{token}/duitnow', [OrderController::class, 'guestDuitNowInstructions'])->name('orders.guest.duitnow');
Route::get('/orders/{order:number}/access/{token}/invoice', [OrderController::class, 'guestInvoice'])->name('orders.guest.invoice');
Route::get('/orders/{order:number}/access/{token}/tracking', ShipmentTrackingController::class)->middleware('throttle:30,1')->name('shipments.guest.track');
Route::get('/orders/{order:number}/access/{token}/returns/create', [ReturnRequestController::class, 'guestCreate'])->name('returns.guest.create');
Route::post('/orders/{order:number}/access/{token}/returns', [ReturnRequestController::class, 'guestStore'])->middleware('throttle:4,1')->name('returns.guest.store');
Route::get('/orders/{order:number}/access/{token}/returns/{returnRequest}', [ReturnRequestController::class, 'guestShow'])->name('returns.guest.show');
Route::get('/orders/{order:number}/access/{token}/returns/{returnRequest}/refunds/{refund}/credit-note', [ReturnRequestController::class, 'guestCreditNote'])->name('returns.guest.credit-note');
Route::get('/orders/{order:number}/access/{token}/returns/{returnRequest}/images/{image}', [ReturnRequestController::class, 'guestDownloadImage'])->name('returns.guest.images.download');
Route::post('/orders/{order:number}/access/{token}/payment-receipt', [PaymentReceiptController::class, 'store'])->middleware('throttle:6,1')->name('orders.payment-receipts.store');
Route::get('/orders/{order:number}/access/{token}/stripe/checkout', [StripeCheckoutController::class, 'start'])->middleware('throttle:6,1')->name('stripe.checkout.start');
Route::post('/orders/{order:number}/access/{token}/stripe/retry', [StripeCheckoutController::class, 'retry'])->middleware('throttle:6,1')->name('stripe.retry');
Route::get('/orders/{order:number}/access/{token}/stripe/cancel', [StripeCheckoutController::class, 'cancel'])->name('stripe.cancel');
Route::get('/stripe/success', [StripeCheckoutController::class, 'success'])->name('stripe.success');
Route::post('/stripe/webhook', StripeWebhookController::class)
    ->withoutMiddleware(VerifyCsrfToken::class)
    ->name('stripe.webhook');

if (app()->environment('local')) {
    Route::prefix('dev/email')->as('dev.email.')->group(function (): void {
        Route::get('order-received', fn () => new TransactionalPreviewMail('order-received'))->name('order-received');
        Route::get('receipt-submitted', fn () => new TransactionalPreviewMail('receipt-submitted'))->name('receipt-submitted');
        Route::get('payment-approved', fn () => new TransactionalPreviewMail('payment-approved'))->name('payment-approved');
        Route::get('receipt-rejected', fn () => new TransactionalPreviewMail('receipt-rejected'))->name('receipt-rejected');
        Route::get('stripe-payment-confirmed', fn () => new TransactionalPreviewMail('stripe-payment-confirmed'))->name('stripe-payment-confirmed');
        Route::get('processing', fn () => new TransactionalPreviewMail('processing'))->name('processing');
        Route::get('packed', fn () => new TransactionalPreviewMail('packed'))->name('packed');
        Route::get('shipped', fn () => new TransactionalPreviewMail('shipped'))->name('shipped');
        Route::get('delivered', fn () => new TransactionalPreviewMail('delivered'))->name('delivered');
        Route::get('cancelled', fn () => new TransactionalPreviewMail('cancelled'))->name('cancelled');
        Route::get('admin/new-order', fn () => new AdminOperationalPreviewMail('new-order'))->name('admin.new-order');
        Route::get('admin/new-duitnow-receipt', fn () => new AdminOperationalPreviewMail('new-duitnow-receipt'))->name('admin.new-duitnow-receipt');
        Route::get('admin/stripe-paid', fn () => new AdminOperationalPreviewMail('stripe-paid'))->name('admin.stripe-paid');
        Route::get('admin/low-stock', fn () => new AdminOperationalPreviewMail('low-stock'))->name('admin.low-stock');
        Route::get('admin/out-of-stock', fn () => new AdminOperationalPreviewMail('out-of-stock'))->name('admin.out-of-stock');
        Route::get('admin/new-review', fn () => new AdminOperationalPreviewMail('new-review'))->name('admin.new-review');
        Route::get('admin/new-newsletter-subscriber', fn () => new AdminOperationalPreviewMail('new-newsletter-subscriber'))->name('admin.new-newsletter-subscriber');
        Route::get('admin/cancelled-order', fn () => new AdminOperationalPreviewMail('cancelled-order'))->name('admin.cancelled-order');
        Route::get('admin/payment-attention', fn () => new AdminOperationalPreviewMail('payment-attention'))->name('admin.payment-attention');
    });
}

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::get('/orders/{order}/returns/create', [ReturnRequestController::class, 'create'])->name('returns.create');
    Route::post('/orders/{order}/returns', [ReturnRequestController::class, 'store'])->middleware('throttle:4,1')->name('returns.store');
    Route::get('/orders/{order}/returns/{returnRequest}', [ReturnRequestController::class, 'show'])->name('returns.show');
    Route::get('/orders/{order}/returns/{returnRequest}/refunds/{refund}/credit-note', [ReturnRequestController::class, 'creditNote'])->name('returns.credit-note');
    Route::get('/orders/{order}/returns/{returnRequest}/images/{image}', [ReturnRequestController::class, 'downloadImage'])->name('returns.images.download');
    Route::get('/orders/{order}/invoice', [OrderController::class, 'invoice'])->name('orders.invoice');
    Route::get('/orders/{order}/confirmation', [OrderController::class, 'confirmation'])->name('orders.confirmation');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth', 'admin'])->prefix('admin')->as('admin.')->group(function (): void {
    Route::get('/', AdminDashboardController::class)->name('dashboard');
    Route::redirect('dashboard', '/admin');
    Route::get('products/stock-notifications', [AdminProductStockNotificationController::class, 'index'])->name('product-stock-notifications.index');
    Route::patch('products/{product}/images/sort', [AdminProductController::class, 'sortImages'])->name('products.images.sort');
    Route::patch('products/{product}/images/{image}/primary', [AdminProductController::class, 'setPrimaryImage'])->name('products.images.primary');
    Route::delete('products/{product}/images/{image}', [AdminProductController::class, 'destroyImage'])->name('products.images.destroy');
    Route::post('products/{product}/variants/generate', [AdminProductController::class, 'generateVariants'])->name('products.variants.generate');
    Route::patch('products/{product}/variants/{variant}', [AdminProductController::class, 'updateVariant'])->name('products.variants.update');
    Route::delete('products/{product}/variants/{variant}', [AdminProductController::class, 'destroyVariant'])->name('products.variants.destroy');
    Route::resource('products', AdminProductController::class)->except('show');
    Route::resource('categories', AdminCategoryController::class)->except('show');
    Route::resource('product-sizes', AdminProductSizeController::class)->except('show');
    Route::resource('product-colours', AdminProductColourController::class)->except('show');
    Route::resource('product-tags', AdminProductTagController::class)->except('show');
    Route::get('orders', [AdminOrderController::class, 'index'])->name('orders.index');
    Route::get('orders/{order}/invoice', [AdminOrderController::class, 'invoice'])->name('orders.invoice');
    Route::get('orders/{order}/packing-slip', [AdminOrderController::class, 'packingSlip'])->name('orders.packing-slip');
    Route::get('orders/{order}/shipments/create', [ShipmentController::class, 'create'])->name('orders.shipments.create');
    Route::post('orders/{order}/shipments', [ShipmentController::class, 'store'])->name('orders.shipments.store');
    Route::get('orders/{order}', [AdminOrderController::class, 'show'])->name('orders.show');
    Route::patch('orders/{order}', [AdminOrderController::class, 'update'])->name('orders.update');
    Route::get('shipments', [ShipmentController::class, 'index'])->name('shipments.index');
    Route::get('shipments/{shipment}', [ShipmentController::class, 'show'])->name('shipments.show');
    Route::post('shipments/{shipment}/ship', [ShipmentController::class, 'ship'])->name('shipments.ship');
    Route::post('shipments/{shipment}/events', [ShipmentController::class, 'storeEvent'])->name('shipments.events.store');
    Route::get('shipments/{shipment}/label', [ShipmentController::class, 'downloadLabel'])->name('shipments.label.download');
    Route::resource('couriers', CourierController::class)->except(['show', 'destroy']);
    Route::get('returns', [AdminReturnRequestController::class, 'index'])->name('returns.index');
    Route::get('returns/{return}', [AdminReturnRequestController::class, 'show'])->name('returns.show');
    Route::patch('returns/{return}/review', [AdminReturnRequestController::class, 'beginReview'])->name('returns.review');
    Route::patch('returns/{return}/approve', [AdminReturnRequestController::class, 'approve'])->name('returns.approve');
    Route::patch('returns/{return}/reject', [AdminReturnRequestController::class, 'reject'])->name('returns.reject');
    Route::patch('returns/{return}/instructions', [AdminReturnRequestController::class, 'instructions'])->name('returns.instructions');
    Route::patch('returns/{return}/received', [AdminReturnRequestController::class, 'received'])->name('returns.received');
    Route::patch('returns/{return}/inspect', [AdminReturnRequestController::class, 'inspect'])->name('returns.inspect');
    Route::patch('returns/{return}/finish-inspection', [AdminReturnRequestController::class, 'finishInspection'])->name('returns.finish-inspection');
    Route::post('returns/{return}/refunds', [AdminReturnRequestController::class, 'refund'])->name('returns.refunds.store');
    Route::patch('refunds/{refund}/manual-confirmation', [AdminReturnRequestController::class, 'confirmManualRefund'])->name('refunds.manual-confirm');
    Route::patch('returns/{return}/exchange', [AdminReturnRequestController::class, 'exchange'])->name('returns.exchange');
    Route::patch('returns/{return}/close', [AdminReturnRequestController::class, 'close'])->name('returns.close');
    Route::get('returns/images/{image}', [AdminReturnRequestController::class, 'downloadImage'])->name('returns.images.download');
    Route::get('refunds/{refund}/proof', [AdminReturnRequestController::class, 'downloadProof'])->name('refunds.proof.download');
    Route::get('refunds/{refund}/credit-note', [AdminReturnRequestController::class, 'creditNote'])->name('refunds.credit-note');
    Route::resource('shipping-zones', ShippingZoneController::class)->except('show');
    Route::resource('delivery-methods', DeliveryMethodController::class)->except('show');
    Route::resource('coupons', AdminCouponController::class)->except('show');
    Route::get('newsletter/campaigns', [NewsletterCampaignController::class, 'index'])->name('newsletter.campaigns.index');
    Route::get('newsletter/campaigns/create', [NewsletterCampaignController::class, 'create'])->name('newsletter.campaigns.create');
    Route::post('newsletter/campaigns', [NewsletterCampaignController::class, 'store'])->name('newsletter.campaigns.store');
    Route::get('newsletter/campaigns/{campaign}', [NewsletterCampaignController::class, 'show'])->name('newsletter.campaigns.show');
    Route::get('newsletter/campaigns/{campaign}/edit', [NewsletterCampaignController::class, 'edit'])->name('newsletter.campaigns.edit');
    Route::put('newsletter/campaigns/{campaign}', [NewsletterCampaignController::class, 'update'])->name('newsletter.campaigns.update');
    Route::get('newsletter/campaigns/{campaign}/preview', [NewsletterCampaignController::class, 'preview'])->name('newsletter.campaigns.preview');
    Route::post('newsletter/campaigns/{campaign}/test', [NewsletterCampaignController::class, 'test'])->middleware('throttle:6,1')->name('newsletter.campaigns.test');
    Route::post('newsletter/campaigns/{campaign}/schedule', [NewsletterCampaignController::class, 'schedule'])->name('newsletter.campaigns.schedule');
    Route::post('newsletter/campaigns/{campaign}/send', [NewsletterCampaignController::class, 'send'])->name('newsletter.campaigns.send');
    Route::post('newsletter/campaigns/{campaign}/duplicate', [NewsletterCampaignController::class, 'duplicate'])->name('newsletter.campaigns.duplicate');
    Route::patch('newsletter/campaigns/{campaign}/archive', [NewsletterCampaignController::class, 'archive'])->name('newsletter.campaigns.archive');
    Route::get('newsletter/campaigns/{campaign}/deliveries', [NewsletterCampaignController::class, 'deliveries'])->name('newsletter.campaigns.deliveries');
    Route::get('newsletter', [NewsletterSubscriberController::class, 'index'])->name('newsletter.index');
    Route::patch('newsletter/{newsletterSubscriber}/unsubscribe', [NewsletterSubscriberController::class, 'unsubscribe'])->name('newsletter.unsubscribe');
    Route::get('newsletter/export', [NewsletterSubscriberController::class, 'export'])->name('newsletter.export');
    Route::delete('newsletter/{newsletterSubscriber}', [NewsletterSubscriberController::class, 'destroy'])->name('newsletter.destroy');
    Route::resource('faqs', AdminFaqController::class)->except('show');
    Route::patch('reviews/bulk', [AdminReviewController::class, 'bulk'])->name('reviews.bulk');
    Route::get('reviews', [AdminReviewController::class, 'index'])->name('reviews.index');
    Route::get('reviews/{review}', [AdminReviewController::class, 'show'])->name('reviews.show');
    Route::patch('reviews/{review}/approve', [AdminReviewController::class, 'approve'])->name('reviews.approve');
    Route::patch('reviews/{review}/reject', [AdminReviewController::class, 'reject'])->name('reviews.reject');
    Route::patch('reviews/{review}/hide', [AdminReviewController::class, 'hide'])->name('reviews.hide');
    Route::patch('reviews/{review}/reply', [AdminReviewController::class, 'reply'])->name('reviews.reply');
    Route::delete('reviews/{review}', [AdminReviewController::class, 'destroy'])->name('reviews.destroy');
    Route::get('customers/export', [AdminCustomerController::class, 'export'])->name('customers.export');
    Route::get('customers', [AdminCustomerController::class, 'index'])->name('customers.index');
    Route::get('customers/{email}', [AdminCustomerController::class, 'show'])->name('customers.show');
    Route::post('customers/{email}/notes', [AdminCustomerController::class, 'storeNote'])->name('customers.notes.store');
    Route::get('reports/export/{report}', [AdminReportsController::class, 'export'])->name('reports.export');
    Route::get('reports', [AdminReportsController::class, 'index'])->name('reports.index');
    Route::prefix('accounting')->as('accounting.')->group(function (): void {
        Route::get('/', [AdminAccountingController::class, 'overview'])->name('overview');
        Route::get('sales-summary', [AdminAccountingController::class, 'salesSummary'])->name('sales-summary');
        Route::get('income', [AdminAccountingController::class, 'income'])->name('income.index');
        Route::post('income', [AdminAccountingController::class, 'storeIncome'])->name('income.store');
        Route::get('expenses', [AdminAccountingController::class, 'expenses'])->name('expenses.index');
        Route::get('expenses/create', [AdminAccountingController::class, 'createExpense'])->name('expenses.create');
        Route::post('expenses', [AdminAccountingController::class, 'storeExpense'])->name('expenses.store');
        Route::get('expenses/{expense}/edit', [AdminAccountingController::class, 'editExpense'])->name('expenses.edit');
        Route::put('expenses/{expense}', [AdminAccountingController::class, 'updateExpense'])->name('expenses.update');
        Route::get('expenses/{expense}/receipt', [AdminAccountingController::class, 'downloadExpenseReceipt'])->name('expenses.receipt.download');
        Route::post('expenses/{expense}/approve', [AdminAccountingController::class, 'approveExpense'])->name('expenses.approve');
        Route::post('expenses/{expense}/post', [AdminAccountingController::class, 'postExpense'])->name('expenses.post');
        Route::post('expenses/{expense}/reverse', [AdminAccountingController::class, 'reverseExpense'])->name('expenses.reverse');
        Route::get('owner-compensation', [AdminAccountingController::class, 'ownerTransactions'])->name('owner-transactions.index');
        Route::get('owner-compensation/create', [AdminAccountingController::class, 'createOwnerTransaction'])->name('owner-transactions.create');
        Route::post('owner-compensation', [AdminAccountingController::class, 'storeOwnerTransaction'])->name('owner-transactions.store');
        Route::get('owner-compensation/{ownerTransaction}/edit', [AdminAccountingController::class, 'editOwnerTransaction'])->name('owner-transactions.edit');
        Route::put('owner-compensation/{ownerTransaction}', [AdminAccountingController::class, 'updateOwnerTransaction'])->name('owner-transactions.update');
        Route::post('owner-compensation/{ownerTransaction}/post', [AdminAccountingController::class, 'postOwnerTransaction'])->name('owner-transactions.post');
        Route::get('chart-of-accounts', [AccountingAccountController::class, 'index'])->name('accounts.index');
        Route::get('chart-of-accounts/create', [AccountingAccountController::class, 'create'])->name('accounts.create');
        Route::post('chart-of-accounts', [AccountingAccountController::class, 'store'])->name('accounts.store');
        Route::get('chart-of-accounts/{account}', [AccountingAccountController::class, 'show'])->name('accounts.show');
        Route::get('chart-of-accounts/{account}/edit', [AccountingAccountController::class, 'edit'])->name('accounts.edit');
        Route::put('chart-of-accounts/{account}', [AccountingAccountController::class, 'update'])->name('accounts.update');
        Route::patch('chart-of-accounts/{account}/toggle-status', [AccountingAccountController::class, 'toggleStatus'])->name('accounts.toggle-status');
        Route::delete('chart-of-accounts/{account}', [AccountingAccountController::class, 'destroy'])->name('accounts.destroy');
        Route::get('journal-entries', [JournalEntryController::class, 'index'])->name('journals.index');
        Route::get('journal-entries/create', [JournalEntryController::class, 'create'])->name('journals.create');
        Route::post('journal-entries', [JournalEntryController::class, 'store'])->name('journals.store');
        Route::get('journal-entries/{journalEntry}', [JournalEntryController::class, 'show'])->name('journals.show');
        Route::get('journal-entries/{journalEntry}/edit', [JournalEntryController::class, 'edit'])->name('journals.edit');
        Route::put('journal-entries/{journalEntry}', [JournalEntryController::class, 'update'])->name('journals.update');
        Route::post('journal-entries/{journalEntry}/post', [JournalEntryController::class, 'post'])->name('journals.post');
        Route::post('journal-entries/{journalEntry}/reverse', [JournalEntryController::class, 'reverse'])->name('journals.reverse');
        Route::post('journal-entries/{journalEntry}/cancel', [JournalEntryController::class, 'cancel'])->name('journals.cancel');
        Route::get('general-ledger', [GeneralLedgerController::class, 'index'])->name('ledger.index');
        Route::get('general-ledger/trial-balance', [GeneralLedgerController::class, 'trialBalance'])->name('ledger.trial-balance');
        Route::get('general-ledger/integrity', [GeneralLedgerController::class, 'integrity'])->name('ledger.integrity');
        Route::get('general-ledger/export/{format}', [GeneralLedgerController::class, 'exportSummary'])->whereIn('format', ['csv', 'xlsx', 'pdf'])->name('ledger.export');
        Route::get('general-ledger/print', [GeneralLedgerController::class, 'printSummary'])->name('ledger.print');
        Route::get('general-ledger/trial-balance/export/{format}', [GeneralLedgerController::class, 'exportTrialBalance'])->whereIn('format', ['csv', 'xlsx', 'pdf'])->name('ledger.trial-balance.export');
        Route::get('general-ledger/accounts/{account}', [GeneralLedgerController::class, 'account'])->name('ledger.account');
        Route::get('general-ledger/accounts/{account}/export/{format}', [GeneralLedgerController::class, 'exportAccount'])->whereIn('format', ['csv', 'xlsx', 'pdf'])->name('ledger.account.export');
        Route::get('general-ledger/accounts/{account}/print', [GeneralLedgerController::class, 'printAccount'])->name('ledger.account.print');
        Route::get('profit-loss', [AdminAccountingController::class, 'profitAndLoss'])->name('profit-loss.index');
        Route::get('cash-flow', [AdminAccountingController::class, 'cashFlow'])->name('cash-flow.index');
        Route::get('financial-settings', [AdminAccountingController::class, 'financialSettings'])->name('settings.index');
        Route::patch('financial-settings', [AdminAccountingController::class, 'updateFinancialSettings'])->name('settings.update');
        Route::get('exports/{report}/{format}', [AdminAccountingController::class, 'export'])->whereIn('report', ['ledger', 'sales-summary', 'profit-loss', 'cash-flow'])->whereIn('format', ['csv', 'xlsx', 'pdf'])->name('exports.download');
    });
    Route::get('settings', [AdminSettingsController::class, 'index'])->name('settings.index');
    Route::patch('settings', [AdminSettingsController::class, 'update'])->name('settings.update');
    Route::post('settings/media', [AdminSettingsController::class, 'uploadMedia'])->name('settings.media.upload');
    Route::get('settings/audit', [AdminSettingsController::class, 'audit'])->name('settings.audit');
    Route::post('settings/cache/clear', [AdminSettingsController::class, 'clearCache'])->name('settings.cache.clear');
    Route::get('payment-receipts', [AdminPaymentReceiptController::class, 'index'])->name('payment-receipts.index');
    Route::get('payment-receipts/{paymentReceipt}', [AdminPaymentReceiptController::class, 'show'])->name('payment-receipts.show');
    Route::patch('payment-receipts/{paymentReceipt}/approve', [AdminPaymentReceiptController::class, 'approve'])->name('payment-receipts.approve');
    Route::patch('payment-receipts/{paymentReceipt}/reject', [AdminPaymentReceiptController::class, 'reject'])->name('payment-receipts.reject');
    Route::get('payment-receipts/{paymentReceipt}/download', [AdminPaymentReceiptController::class, 'download'])->name('payment-receipts.download');
});

require __DIR__.'/auth.php';
