<x-layouts.admin :title="$entry->entry_number.' | Cherry Bellemont'">
    <x-admin.section width="7xl">
        <x-admin.page-header eyebrow="Accounting journal" :title="$entry->entry_number" :subtitle="$entry->description">
            <x-slot:actions>
                <x-admin.button variant="outline" :href="route('admin.accounting.journals.index')">All Journals</x-admin.button>
                @if($entry->isDraft())<x-admin.button variant="outline" :href="route('admin.accounting.journals.edit', $entry)" icon="bi-pencil">Edit Draft</x-admin.button><form method="POST" action="{{ route('admin.accounting.journals.cancel', $entry) }}">@csrf<x-admin.button variant="danger" type="submit" icon="bi-x-circle">Cancel Draft</x-admin.button></form><form method="POST" action="{{ route('admin.accounting.journals.post', $entry) }}">@csrf<x-admin.button variant="success" type="submit" icon="bi-journal-check">Post Journal</x-admin.button></form>@elseif($entry->status === 'posted')<form class="flex gap-3" method="POST" action="{{ route('admin.accounting.journals.reverse', $entry) }}">@csrf<input class="admin-field w-48" name="reason" maxlength="500" placeholder="Reversal reason (optional)"><x-admin.button variant="danger" type="submit" icon="bi-arrow-counterclockwise">Reverse</x-admin.button></form>@endif
            </x-slot:actions>
        </x-admin.page-header>
        @error('journal')<p class="mt-6 border border-red-300/40 bg-red-950/30 px-4 py-3 text-sm text-red-100">{{ $message }}</p>@enderror
        <div class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><x-admin.stats-card label="Status" :value="str($entry->status)->title()" /><x-admin.stats-card label="Total Debit" :value="'RM '.number_format((float) $entry->total_debit, 2)" /><x-admin.stats-card label="Total Credit" :value="'RM '.number_format((float) $entry->total_credit, 2)" /><x-admin.stats-card label="Balanced" :value="$entry->isBalanced() ? 'Yes' : 'No'" /></div>
        <div class="mt-6 grid gap-6 lg:grid-cols-3"><x-admin.card class="lg:col-span-2" title="Journal header"><dl class="grid gap-x-8 gap-y-5 sm:grid-cols-2"><div><dt class="admin-label">Transaction date</dt><dd>{{ $entry->transaction_date?->format('d M Y') }}</dd></div><div><dt class="admin-label">Posting date</dt><dd>{{ $entry->posting_date?->format('d M Y, H:i') ?: 'Not posted' }}</dd></div><div><dt class="admin-label">Reference</dt><dd>{{ $entry->reference ?: '—' }}</dd></div><div><dt class="admin-label">Source</dt><dd>{{ $entry->sourceLabel() }}</dd></div><div><dt class="admin-label">Posted by</dt><dd>{{ $entry->poster?->name ?: '—' }}</dd></div><div><dt class="admin-label">Reversal</dt><dd>@if($entry->reversalEntry)<a class="text-gold" href="{{ route('admin.accounting.journals.show', $entry->reversalEntry) }}">{{ $entry->reversalEntry->entry_number }}</a>@else — @endif</dd></div></dl></x-admin.card><x-admin.card title="Audit"><dl class="space-y-4 text-sm"><div><dt class="admin-label">Created</dt><dd>{{ $entry->created_at?->format('d M Y, H:i') }} @if($entry->creator) by {{ $entry->creator->name }}@endif</dd></div><div><dt class="admin-label">Updated</dt><dd>{{ $entry->updated_at?->format('d M Y, H:i') }} @if($entry->updater) by {{ $entry->updater->name }}@endif</dd></div><div><dt class="admin-label">Reversed</dt><dd>{{ $entry->reversed_at?->format('d M Y, H:i') ?: '—' }}</dd></div></dl></x-admin.card></div>
        <x-admin.card class="mt-6" title="Journal lines"><x-admin.table class="mt-5"><x-slot:head><tr><th>Account Code</th><th>Account Name</th><th>Description</th><th>Debit</th><th>Credit</th></tr></x-slot:head>@foreach($entry->lines as $line)<tr><td class="text-gold">{{ $line->account?->code ?: '—' }}</td><td>{{ $line->account?->name ?: 'Unavailable account' }}</td><td>{{ $line->description ?: '—' }}</td><td>RM {{ number_format((float) $line->debit, 2) }}</td><td>RM {{ number_format((float) $line->credit, 2) }}</td></tr>@endforeach<tfoot><tr class="font-semibold text-cream"><td colspan="3">Totals</td><td>RM {{ number_format((float) $entry->total_debit, 2) }}</td><td>RM {{ number_format((float) $entry->total_credit, 2) }}</td></tr></tfoot></x-admin.table><p class="mt-5 text-sm {{ $entry->isBalanced() ? 'text-gold' : 'text-red-200' }}"><i class="bi {{ $entry->isBalanced() ? 'bi-check-circle' : 'bi-exclamation-triangle' }} mr-2"></i>{{ $entry->isBalanced() ? 'Balanced: total debits equal total credits.' : 'Unbalanced: posting is blocked until the lines are corrected.' }}</p></x-admin.card>
    </x-admin.section>
</x-layouts.admin>
