<x-layouts.admin title="Sales Summary | Cherry Bellemont">
    <x-admin.section width="7xl">
        <x-admin.page-header eyebrow="Financial sales" title="Sales Summary" subtitle="Confirmed paid orders and completed refunds only. Operational Reports remains separate." />
        <div class="mt-8">@include('admin.accounting.partials.period-filter', ['action' => route('admin.accounting.sales-summary'), 'filters' => $filters, 'rangeOptions' => $rangeOptions, 'ledger' => false])</div>
        <div class="mt-6 flex flex-wrap gap-3"><x-admin.button variant="outline" :href="route('admin.accounting.exports.download', array_merge(['report' => 'sales-summary', 'format' => 'csv'], $filters))" icon="bi-filetype-csv">CSV</x-admin.button><x-admin.button variant="outline" :href="route('admin.accounting.exports.download', array_merge(['report' => 'sales-summary', 'format' => 'xlsx'], $filters))" icon="bi-file-earmark-excel">XLSX</x-admin.button><x-admin.button variant="outline" :href="route('admin.accounting.exports.download', array_merge(['report' => 'sales-summary', 'format' => 'pdf'], $filters))" icon="bi-file-earmark-pdf">PDF</x-admin.button></div>
        <div class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach(['paid_order_count'=>'Paid Orders','gross_product_sales'=>'Gross Product Sales','shipping_income'=>'Shipping Income','gift_wrapping_income'=>'Gift Wrapping Income','discounts'=>'Discounts','gross_sales'=>'Gross Sales','refunds'=>'Refunds','net_sales'=>'Net Sales','average_order_value'=>'Average Order Value','estimated_cost_of_goods_sold'=>'Estimated COGS','estimated_gross_profit'=>'Estimated Gross Profit','stripe_sales'=>'Stripe Sales','duitnow_sales'=>'DuitNow Sales'] as $key=>$label)<x-admin.stats-card :label="$label" :value="in_array($key,['paid_order_count']) ? $summary[$key] : 'RM '.number_format($summary[$key]/100,2)" />@endforeach</div>
        <div class="mt-8 grid gap-6 xl:grid-cols-2"><x-admin.card title="Gross and net sales over time"><div class="admin-chart-canvas mt-6"><canvas id="accounting-gross-sales-chart"></canvas></div></x-admin.card><x-admin.card title="Paid orders and refunds"><div class="admin-chart-canvas mt-6"><canvas id="accounting-refunds-chart"></canvas></div></x-admin.card></div>
        <div class="mt-8 grid gap-6 xl:grid-cols-2">
            @foreach(['payment_methods'=>'Sales by Payment Method','products'=>'Sales by Product','categories'=>'Sales by Category','customers'=>'Sales by Customer','discounts'=>'Discounts Used','refunds'=>'Refund Summary'] as $key=>$title)
                <x-admin.card :title="$title"><x-admin.table class="mt-5"><x-slot:head><tr><th>Name</th><th>Orders / Units</th><th>Net / Amount</th></tr></x-slot:head>@forelse($summary['breakdowns'][$key] as $row)<tr><td>{{ $row['name'] ?? $row['reference'] }}</td><td>{{ $row['order_count'] ?? $row['units_sold'] ?? $row['uses'] ?? '—' }}</td><td>RM {{ number_format(($row['net_sales'] ?? $row['amount'] ?? $row['discounts'] ?? 0)/100,2) }}</td></tr>@empty<tr><td colspan="3" class="text-cream/60">No data in this period.</td></tr>@endforelse</x-admin.table></x-admin.card>
            @endforeach
        </div>
        <script id="accounting-sales-summary-chart-data" type="application/json">@json($summary['charts'])</script>
    </x-admin.section>
</x-layouts.admin>
