<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AccountingAccountRequest;
use App\Http\Requests\AccountingDateRangeRequest;
use App\Http\Requests\AccountingSettingsRequest;
use App\Http\Requests\ExpenseRequest;
use App\Http\Requests\JournalEntryRequest;
use App\Http\Requests\ManualIncomeRequest;
use App\Models\AccountingAccount;
use App\Models\AccountingAuditLog;
use App\Models\Expense;
use App\Models\ExpenseCategory;
use App\Models\JournalEntry;
use App\Services\AccountingAccountService;
use App\Services\AccountingAuditService;
use App\Services\AccountingExportService;
use App\Services\AccountingPostingService;
use App\Services\AccountingReportService;
use App\Services\AccountingSettingsService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class AccountingController extends Controller
{
    public function overview(AccountingDateRangeRequest $request, AccountingReportService $reports): View { return view('admin.accounting.overview', ['overview' => $reports->overview($request->filters()), 'filters' => $request->filters(), 'rangeOptions' => $reports->rangeOptions()]); }
    public function salesSummary(AccountingDateRangeRequest $request, AccountingReportService $reports): View { return view('admin.accounting.sales-summary', ['summary' => $reports->salesSummary($request->filters()), 'filters' => $request->filters(), 'rangeOptions' => $reports->rangeOptions(true)]); }

    public function income(AccountingDateRangeRequest $request, AccountingReportService $reports): View
    {
        $period = $reports->period($request->filters());
        return view('admin.accounting.income', ['period' => $period, 'filters' => $request->filters(), 'rangeOptions' => $reports->rangeOptions(), 'incomeEntries' => JournalEntry::query()->with('lines.account')->posted()->whereBetween('transaction_date', [$period['start'], $period['end']])->whereIn('source_type', ['order', 'manual_income'])->latest('transaction_date')->paginate(25)->withQueryString(), 'revenueAccounts' => AccountingAccount::query()->active()->where('type', 'revenue')->orderBy('code')->get(), 'depositAccounts' => AccountingAccount::query()->active()->where('type', 'asset')->orderBy('code')->get()]);
    }

    public function storeIncome(ManualIncomeRequest $request, AccountingPostingService $posting): RedirectResponse
    {
        $data = $request->validated();
        $entry = $posting->createDraft(['transaction_date' => $data['transaction_date'], 'source_type' => 'manual_income', 'source_id' => null, 'source_event' => null, 'reference' => $data['reference'] ?? null, 'description' => $data['description']], [['account_id' => $data['deposit_account_id'], 'description' => 'Income received', 'debit' => $data['amount'], 'credit' => '0.00'], ['account_id' => $data['revenue_account_id'], 'description' => $data['description'], 'debit' => '0.00', 'credit' => $data['amount']]], $request->user()->id);
        $posting->postDraft($entry, $request->user()->id);
        return back()->with('success', 'Manual income has been posted.');
    }

    public function expenses(Request $request): View { $expenses = Expense::query()->with(['category', 'debitAccount', 'paymentAccount', 'journalEntry'])->latest('expense_date')->when($request->filled('status'), fn ($query) => $query->where('status', $request->string('status')))->when($request->filled('search'), fn ($query) => $query->where(fn ($q) => $q->where('expense_number', 'like', '%'.$request->string('search').'%')->orWhere('supplier', 'like', '%'.$request->string('search').'%')->orWhere('description', 'like', '%'.$request->string('search').'%')))->paginate(25)->withQueryString(); return view('admin.accounting.expenses.index', compact('expenses')); }
    public function createExpense(): View { return view('admin.accounting.expenses.form', $this->expenseForm()); }
    public function storeExpense(ExpenseRequest $request, AccountingAuditService $audit): RedirectResponse { $data = $request->validated(); if ($request->hasFile('receipt')) $data['receipt_path'] = $request->file('receipt')->store('accounting-expenses', 'local'); $expense = Expense::query()->create($data + ['expense_number' => $this->number('EXP', Expense::class, 'expense_number'), 'status' => 'draft', 'created_by' => $request->user()->id, 'updated_by' => $request->user()->id]); $audit->record('expense.created', $expense, $request->user()->id, [], ['status' => 'draft'], $request->ip()); return to_route('admin.accounting.expenses.edit', $expense)->with('success', 'Expense draft created.'); }
    public function showExpense(Expense $expense): View { $expense->load(['category', 'debitAccount', 'paymentAccount', 'journalEntry', 'approver']); return view('admin.accounting.expenses.show', compact('expense')); }
    public function editExpense(Expense $expense): View { abort_if(in_array($expense->status, ['posted', 'reversed', 'voided'], true), 409, 'Finalised expenses cannot be edited. Create a reversal or adjustment instead.'); return view('admin.accounting.expenses.form', $this->expenseForm(['expense' => $expense])); }
    public function updateExpense(ExpenseRequest $request, Expense $expense): RedirectResponse { abort_if(in_array($expense->status, ['posted', 'reversed', 'voided'], true), 409); $data = $request->validated(); if ($request->hasFile('receipt')) $data['receipt_path'] = $request->file('receipt')->store('accounting-expenses', 'local'); $expense->update($data + ['updated_by' => $request->user()->id]); return to_route('admin.accounting.expenses.edit', $expense)->with('success', 'Expense draft updated.'); }
    public function downloadExpenseReceipt(Expense $expense) { abort_unless($expense->receipt_path && Storage::disk('local')->exists($expense->receipt_path), 404); return Storage::disk('local')->download($expense->receipt_path, 'expense-receipt-'.$expense->expense_number.'.'.pathinfo($expense->receipt_path, PATHINFO_EXTENSION)); }
    public function approveExpense(Request $request, Expense $expense, AccountingAuditService $audit): RedirectResponse { abort_unless($expense->status === 'draft', 422); $expense->update(['status' => 'approved', 'approved_by' => $request->user()->id, 'updated_by' => $request->user()->id]); $audit->record('expense.approved', $expense, $request->user()->id, ['status' => 'draft'], ['status' => 'approved'], $request->ip()); return back()->with('success', 'Expense approved and ready to post.'); }
    public function postExpense(Request $request, Expense $expense, AccountingPostingService $posting, AccountingSettingsService $settings): RedirectResponse { if (filter_var($settings->get('require_expense_approval', '1'), FILTER_VALIDATE_BOOL)) abort_unless($expense->status === 'approved', 422, 'This expense requires approval before posting.'); abort_unless(in_array($expense->status, ['draft', 'approved'], true), 422); $posting->postExpense($expense, $request->user()->id); return to_route('admin.accounting.expenses.index')->with('success', 'Expense posted to the General Ledger.'); }
    public function reverseExpense(Request $request, Expense $expense, AccountingPostingService $posting): RedirectResponse { abort_unless($expense->journalEntry, 422); $posting->reverse($expense->journalEntry, $request->user()->id, 'Expense reversal'); $expense->update(['status' => 'reversed']); return back()->with('success', 'Expense was reversed through a balancing journal.'); }
    public function voidExpense(Request $request, Expense $expense, AccountingAuditService $audit): RedirectResponse { abort_unless(in_array($expense->status, ['draft', 'approved'], true), 422, 'Only unposted expenses may be voided.'); $old = $expense->only(['status']); $expense->update(['status' => 'voided', 'updated_by' => $request->user()->id]); $audit->record('expense.voided', $expense, $request->user()->id, $old, ['status' => 'voided'], $request->ip()); return to_route('admin.accounting.expenses.index')->with('success', 'Unposted expense voided. No journal entry was created.'); }

    public function accounts(Request $request, AccountingAccountService $service): View { $service->ensureDefaults(); $accounts = AccountingAccount::query()->withCount('lines')->orderBy('code')->paginate(50); return view('admin.accounting.accounts.index', compact('accounts')); }
    public function createAccount(): View { return view('admin.accounting.accounts.form', ['account' => null, 'parents' => AccountingAccount::query()->active()->orderBy('code')->get()]); }
    public function storeAccount(AccountingAccountRequest $request, AccountingAuditService $audit): RedirectResponse { $account = AccountingAccount::query()->create($request->validated() + ['is_active' => $request->boolean('is_active', true), 'is_system' => false, 'created_by' => $request->user()->id, 'updated_by' => $request->user()->id]); $audit->record('account.created', $account, $request->user()->id, [], $account->only(['code', 'name', 'type']), $request->ip()); return to_route('admin.accounting.accounts.index')->with('success', 'Account created.'); }
    public function editAccount(AccountingAccount $account): View { return view('admin.accounting.accounts.form', ['account' => $account, 'parents' => AccountingAccount::query()->active()->whereKeyNot($account->id)->orderBy('code')->get()]); }
    public function updateAccount(AccountingAccountRequest $request, AccountingAccount $account, AccountingAuditService $audit): RedirectResponse { if ($account->is_system && $request->input('code') !== $account->code) throw ValidationException::withMessages(['code' => 'System account codes cannot be changed.']); if ($account->is_system && ! $request->boolean('is_active') && $account->lines()->exists()) throw ValidationException::withMessages(['is_active' => 'A system account with posted activity cannot be deactivated.']); $old = $account->only(['code', 'name', 'type', 'is_active']); $account->update($request->validated() + ['is_active' => $request->boolean('is_active'), 'updated_by' => $request->user()->id]); $audit->record('account.updated', $account, $request->user()->id, $old, $account->only(['code', 'name', 'type', 'is_active']), $request->ip()); return to_route('admin.accounting.accounts.index')->with('success', 'Account updated.'); }
    public function destroyAccount(AccountingAccount $account): RedirectResponse { abort_if($account->is_system || $account->lines()->exists(), 422, 'System accounts and accounts with journal activity cannot be deleted. Deactivate the account instead.'); $account->delete(); return back()->with('success', 'Unused account deleted.'); }

    public function journals(Request $request): View { $entries = JournalEntry::query()->withCount('lines')->with('poster')->latest('transaction_date')->when($request->filled('status'), fn ($query) => $query->where('status', $request->string('status')))->paginate(25)->withQueryString(); return view('admin.accounting.journals.index', compact('entries')); }
    public function createJournal(): View { return view('admin.accounting.journals.form', ['accounts' => AccountingAccount::query()->active()->orderBy('code')->get(), 'entry' => null]); }
    public function storeJournal(JournalEntryRequest $request, AccountingPostingService $posting): RedirectResponse { $data = $request->validated(); $entry = $posting->createDraft(['transaction_date' => $data['transaction_date'], 'reference' => $data['reference'] ?? null, 'description' => $data['description']], $data['lines'], $request->user()->id); return to_route('admin.accounting.journals.show', $entry)->with('success', 'Balanced journal draft created.'); }
    public function showJournal(JournalEntry $journalEntry): View { return view('admin.accounting.journals.show', ['entry' => $journalEntry->load('lines.account', 'poster', 'reversalEntry')]); }
    public function postJournal(Request $request, JournalEntry $journalEntry, AccountingPostingService $posting): RedirectResponse { $posting->postDraft($journalEntry, $request->user()->id); return back()->with('success', 'Journal entry posted.'); }
    public function reverseJournal(Request $request, JournalEntry $journalEntry, AccountingPostingService $posting): RedirectResponse { $posting->reverse($journalEntry, $request->user()->id, $request->string('reason')->trim()->value() ?: null); return back()->with('success', 'A balanced reversal entry has been posted.'); }

    public function ledger(AccountingDateRangeRequest $request, AccountingReportService $reports): View { return view('admin.accounting.ledger', ['ledger' => $reports->ledger($request->filters()), 'filters' => $request->filters(), 'rangeOptions' => $reports->rangeOptions()]); }
    public function profitAndLoss(AccountingDateRangeRequest $request, AccountingReportService $reports): View { return view('admin.accounting.profit-loss', ['report' => $reports->profitAndLoss($request->filters()), 'filters' => $request->filters(), 'rangeOptions' => $reports->rangeOptions()]); }
    public function financialSettings(AccountingAccountService $accounts, AccountingSettingsService $settings): View { $accounts->ensureDefaults(); return view('admin.accounting.settings', ['settings' => $settings->all(), 'accounts' => AccountingAccount::query()->active()->orderBy('code')->get(), 'auditLogs' => AccountingAuditLog::query()->with('user')->latest()->limit(25)->get()]); }
    public function updateFinancialSettings(AccountingSettingsRequest $request, AccountingSettingsService $settings, AccountingAuditService $audit): RedirectResponse { $values = $request->validated(); $this->assertSettingAccountTypes($values); foreach ($values as $key => $value) $settings->set($key, is_bool($value) ? (int) $value : $value, $request->user()->id); $settings->forgetCache(); $audit->record('financial_settings.updated', (object) ['id' => null], $request->user()->id, [], ['keys' => array_keys($values)], $request->ip()); return back()->with('success', 'Financial settings saved.'); }

    public function export(string $report, string $format, AccountingDateRangeRequest $request, AccountingReportService $reports, AccountingExportService $exports): \Symfony\Component\HttpFoundation\Response
    {
        abort_unless(in_array($report, ['ledger', 'sales-summary', 'profit-loss', 'cash-flow'], true) && in_array($format, ['csv', 'xlsx', 'pdf'], true), 404);
        $filters = $request->filters(); $data = match ($report) { 'ledger' => $reports->ledger($filters), 'sales-summary' => $reports->salesSummary($filters), 'profit-loss' => $reports->profitAndLoss($filters), default => $reports->cashFlow($filters) };
        [$title, $headings, $rows, $period] = $this->exportRows($report, $data);
        return $exports->download($format, 'cherry-bellemont-'.str_replace('-', '_', $report), $title, $period, $headings, $rows);
    }

    private function expenseForm(array $extra = []): array { return $extra + ['categories' => ExpenseCategory::query()->where('is_active', true)->orderBy('sort_order')->get(), 'accounts' => AccountingAccount::query()->active()->orderBy('code')->get()]; }
    private function number(string $prefix, string $model, string $column): string { return $prefix.'-'.now()->format('Y').'-'.str_pad((string) ((int) $model::query()->max('id') + 1), 6, '0', STR_PAD_LEFT); }
    private function assertSettingAccountTypes(array $values): void { $expected = ['default_bank_account'=>'asset','default_cash_account'=>'asset','stripe_clearing_account'=>'asset','duitnow_clearing_account'=>'asset','product_sales_account'=>'revenue','shipping_income_account'=>'revenue','gift_wrapping_income_account'=>'revenue','sales_discount_account'=>'revenue','refund_account'=>'revenue','inventory_asset_account'=>'asset','cost_of_goods_sold_account'=>'cost_of_goods_sold','payment_processing_fee_account'=>'expense','owner_salary_account'=>'expense','owner_drawings_account'=>'equity','owner_capital_account'=>'equity','business_reserve_account'=>'equity','emergency_reserve_account'=>'equity','retained_earnings_account'=>'equity']; $accounts = AccountingAccount::query()->whereIn('code', array_intersect_key($values, $expected))->get()->keyBy('code'); foreach ($expected as $key => $type) { $account = $accounts->get($values[$key]); if (! $account || ! $account->is_active || $account->type !== $type) throw ValidationException::withMessages([$key => 'Select an active '.$type.' account for this mapping.']); } }
    private function exportRows(string $report, array $data): array { if ($report === 'ledger') return ['General Ledger', ['Date','Posting Date','Journal Entry','Account','Description','Reference','Source','Debit','Credit','Running Balance'], $data['rows']->map(fn ($row) => [$row['line']->journalEntry->transaction_date->toDateString(), optional($row['line']->journalEntry->posting_date)->toDateString(), $row['line']->journalEntry->entry_number, $row['line']->account->code.' '.$row['line']->account->name, $row['line']->description, $row['line']->journalEntry->reference, $row['line']->journalEntry->source_type, number_format(((float) $row['line']->debit),2), number_format(((float) $row['line']->credit),2), number_format($row['running_balance']/100,2)]), $data['period']]; if ($report === 'sales-summary') return ['Sales Summary', ['Metric','Amount (MYR)'], collect(['Paid Orders' => $data['paid_order_count'], 'Gross Product Sales' => $data['gross_product_sales']/100, 'Shipping Income' => $data['shipping_income']/100, 'Gift Wrapping Income' => $data['gift_wrapping_income']/100, 'Discounts' => -$data['discounts']/100, 'Gross Sales' => $data['gross_sales']/100, 'Refunds' => -$data['refunds']/100, 'Net Sales' => $data['net_sales']/100, 'Estimated Cost of Goods Sold' => $data['estimated_cost_of_goods_sold']/100, 'Estimated Gross Profit' => $data['estimated_gross_profit']/100])->map(fn ($amount, $label) => [$label, number_format($amount, 2)]), $data['period']]; if ($report === 'profit-loss') return ['Profit & Loss', ['Account','Amount (MYR)'], collect($data['revenue'])->merge($data['cost_of_goods_sold_lines'])->merge($data['expenses'])->map(fn ($row) => [$row['account']->code.' '.$row['account']->name, number_format($row['amount']/100, 2)]), $data['period']]; return ['Cash Flow', ['Metric','Amount (MYR)'], collect(['Opening Cash Balance' => $data['opening_balance'], 'Cash Inflow' => $data['cash_inflow'], 'Cash Outflow' => -$data['cash_outflow'], 'Net Cash Movement' => $data['net_cash_movement'], 'Closing Cash Balance' => $data['closing_balance']])->map(fn ($amount, $label) => [$label, number_format($amount/100, 2)]), $data['period']]; }
}
