<x-layouts.admin :title="($transaction ? 'Edit' : 'New').' Owner Transaction | Cherry Bellemont'">
    <x-admin.section width="5xl"><x-admin.page-header eyebrow="Accounting" :title="$transaction ? 'Edit Owner Transaction' : 'Owner Compensation'" subtitle="Drawings and reserve allocations do not reduce operating profit." />
        <x-admin.card class="mt-8"><form id="owner-transaction-form" class="grid gap-5 md:grid-cols-2" method="POST" action="{{ $transaction ? route('admin.accounting.owner-transactions.update',$transaction) : route('admin.accounting.owner-transactions.store') }}">@csrf@if($transaction)@method('PUT')@endif
            <x-admin.form-input name="transaction_date" type="date" label="Transaction date" :value="$transaction?->transaction_date?->toDateString() ?? now()->toDateString()" required />
            <x-admin.select name="transaction_type" label="Transaction type" required>@foreach(['owner_salary'=>'Owner Salary','owner_drawing'=>'Owner Drawing','owner_capital'=>'Owner Capital Contribution','business_reserve_allocation'=>'Business Reserve Allocation','emergency_reserve_allocation'=>'Emergency Reserve Allocation','retained_earnings_allocation'=>'Retained Earnings Allocation'] as $value=>$label)<option value="{{ $value }}" @selected(old('transaction_type',$transaction?->transaction_type)===$value)>{{ $label }}</option>@endforeach</x-admin.select>
            <x-admin.form-input name="amount" type="number" step="0.01" min="0.01" label="Amount (MYR)" :value="$transaction?->amount" required /><x-admin.form-input name="payment_method" label="Payment method" :value="$transaction?->payment_method" />
            <x-admin.select name="payment_account_id" label="Cash / source account" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('payment_account_id',$transaction?->payment_account_id)===$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</x-admin.select><x-admin.select name="destination_account_id" label="Destination account" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(old('destination_account_id',$transaction?->destination_account_id)===$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</x-admin.select>
            <x-admin.form-input name="reference_number" label="Reference number" :value="$transaction?->reference_number" /><x-admin.form-input class="md:col-span-2" name="description" label="Description" :value="$transaction?->description" required /><x-admin.textarea class="md:col-span-2" name="notes" label="Notes">{{ old('notes',$transaction?->notes) }}</x-admin.textarea>
        </form><div class="mt-6 flex gap-3"><x-admin.button form="owner-transaction-form" type="submit" icon="bi-save">Save Draft</x-admin.button>@if($transaction)<form method="POST" action="{{ route('admin.accounting.owner-transactions.post',$transaction) }}">@csrf<x-admin.button variant="success" type="submit" icon="bi-journal-check">Post Transaction</x-admin.button></form>@endif</div></x-admin.card>
    </x-admin.section>
</x-layouts.admin>
